name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: pip install docker pytest pytest-timeout

      - name: Build sandbox image
        run: docker build -t sandbox-python ./src/sandbox

      - name: Run tests
        run: python -m pytest -s --timeout=10