name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          cache: "pip"

      - name: Install dependencies
        run: pip install docker pytest pytest-timeout
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build sandbox image (cached)
        uses: docker/build-push-action@v5
        with:
          context: ./src/sandbox
          tags: sandbox-python:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        run: python -m pytest -s --timeout=10